import { Injectable } from '@nestjs/common';

import type { PerformanceAgentRuntimeConfig } from '../../domain/agents/performance-agent.types';

@Injectable()
export class PerformanceAgentRuntimeConfigService {
  public getRuntimeConfig(): PerformanceAgentRuntimeConfig {
    return {
      schemaVersion: '1.0',
      orchestratorVersion: '1.0.0',
      optionalAgentNames: [
        'segmentation_specialist',
        'search_terms_specialist',
        'creative_performance',
      ],
      thresholds: {
        min_account_conversions: 12,
        min_account_clicks: 120,
        min_campaign_clicks: 30,
        min_campaign_conversions: 3,
        min_campaign_spend_brl: 180,
        account_cpa_warning_delta_pct: 15,
        account_roas_warning_delta_pct: -10,
        account_conversion_drop_pct: -12,
        account_spend_growth_guard_pct: 5,
        account_volume_drop_pct: -20,
        account_scale_cpa_multiplier: 0.9,
        account_scale_roas_multiplier: 1.1,
        account_scale_conversion_growth_pct: 8,
        account_min_consistent_windows: 2,
        account_volatility_cpa_spread_pct: 20,
        account_volatility_roas_spread_pct: 18,
        campaign_cpa_gap_multiplier: 1.25,
        campaign_roas_gap_multiplier: 0.8,
        campaign_peer_cpa_gap_multiplier: 1.2,
        campaign_peer_roas_gap_multiplier: 0.85,
        campaign_scale_cpa_multiplier: 0.92,
        campaign_scale_roas_multiplier: 1.03,
        campaign_scale_min_conversion_growth_pct: 8,
        campaign_contain_min_spend_share_pct: 12,
        campaign_pause_min_clicks: 80,
        campaign_pause_max_conversions: 1,
        campaign_pause_min_spend_brl: 350,
        campaign_pause_roas_max: 0.7,
        campaign_pause_min_spend_share_pct: 8,
        campaign_investigate_cpa_growth_pct: 18,
        campaign_investigate_conversion_drop_pct: -18,
        campaign_concentration_warn_spend_share_pct: 30,
        campaign_concentration_high_spend_share_pct: 45,
        campaign_budget_limited_search_impression_share_pct: 0.55,
        campaign_budget_limited_min_conversions: 8,
        segmentation_spend_floor_brl: 120,
        segmentation_min_clicks: 25,
        segmentation_min_conversions: 2,
        segmentation_time_waste_cpa_gap_multiplier: 1.35,
        segmentation_time_waste_cvr_ratio: 0.65,
        segmentation_time_winner_roas_multiplier: 1.18,
        segmentation_time_winner_cpa_multiplier: 0.85,
        segmentation_geo_high_cpa_multiplier: 1.45,
        segmentation_geo_opportunity_roas_multiplier: 1.15,
        segmentation_geo_opportunity_cpa_multiplier: 0.9,
        segmentation_device_low_cvr_ratio: 0.55,
        segmentation_device_high_clicks_min: 60,
        segmentation_device_winner_roas_multiplier: 1.12,
        segmentation_device_winner_cvr_ratio: 1.12,
        segmentation_trend_cpa_growth_pct: 15,
        segmentation_trend_conversion_drop_pct: -15,
        search_terms_min_clicks: 8,
        search_terms_min_spend_brl: 40,
        search_terms_waste_min_clicks: 20,
        search_terms_waste_min_spend_brl: 80,
        search_terms_exploration_max_clicks: 18,
        search_terms_exploration_max_spend_brl: 70,
        search_terms_irrelevant_min_clicks: 12,
        search_terms_irrelevant_min_spend_brl: 55,
        search_terms_opportunity_min_clicks: 15,
        search_terms_opportunity_min_conversions: 2,
        search_terms_opportunity_roas_multiplier: 1.15,
        search_terms_opportunity_cpa_multiplier: 0.9,
        search_terms_concentration_top_share_pct: 65,
        search_terms_concentration_min_waste_terms: 3,
        search_terms_irrelevant_token_patterns:
          'gratis,free,emprego,vaga,curso,como fazer,manual,pdf,mercado livre,olx,reclame aqui,telefone,whatsapp',
        creative_min_clicks: 35,
        creative_min_impressions: 5000,
        creative_min_spend_brl: 180,
        creative_ctr_drop_pct: -15,
        creative_cvr_drop_pct: -18,
        creative_cpa_growth_pct: 15,
        creative_low_ctr_ratio_vs_account: 0.75,
        creative_low_ctr_ratio_vs_baseline: 0.82,
        creative_misalignment_min_clicks: 45,
        creative_misalignment_ctr_ratio_vs_account: 0.9,
        creative_misalignment_cvr_ratio_vs_account: 0.6,
        creative_misalignment_cpa_multiplier: 1.15,
        creative_refresh_ctr_ratio_vs_account: 0.82,
        creative_refresh_cvr_ratio_vs_baseline: 0.7,
        creative_refresh_min_spend_brl: 250,
        hypothesis_review_stale_sync_penalty: 0.08,
        hypothesis_review_data_gap_penalty: 0.05,
        hypothesis_review_missing_baseline_penalty: 0.1,
        hypothesis_review_soft_conflict_penalty: 0.08,
        hypothesis_review_hard_conflict_penalty: 0.18,
        hypothesis_review_support_agent_bonus: 0.03,
        hypothesis_review_min_evidence_confirmed: 3,
        hypothesis_review_min_evidence_plausible: 2,
        hypothesis_review_min_confidence_confirmed: 0.82,
        hypothesis_review_min_confidence_plausible: 0.62,
        hypothesis_review_min_confidence_weak: 0.45,
        hypothesis_review_discard_weak_below_priority: 45,
        hypothesis_review_discard_insufficient_below_priority: 60,
        hypothesis_review_max_merged_evidence: 8,
        stale_sync_hours: 18,
      },
    };
  }
}
