-- Schema inicial para SaaS multi-tenant de Google Ads analytics
-- Referencia: 2026-04-06
-- Compatibilidade alvo: MySQL 8 / InnoDB / utf8mb4

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE tenants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(160) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    status ENUM('active', 'suspended', 'pending') NOT NULL DEFAULT 'active',
    timezone VARCHAR(64) NOT NULL DEFAULT 'America/Sao_Paulo',
    currency_code CHAR(3) NOT NULL DEFAULT 'BRL',
    plan_code VARCHAR(40) NULL,
    data_key_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tenants_uuid (uuid),
    UNIQUE KEY uq_tenants_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid CHAR(36) NOT NULL,
    name VARCHAR(160) NOT NULL,
    email VARCHAR(191) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    platform_role ENUM('none', 'superadmin') NOT NULL DEFAULT 'none',
    status ENUM('active', 'blocked', 'pending') NOT NULL DEFAULT 'active',
    mfa_enabled TINYINT(1) NOT NULL DEFAULT 0,
    mfa_secret_ciphertext VARBINARY(512) NULL,
    mfa_secret_iv VARBINARY(64) NULL,
    mfa_secret_tag VARBINARY(64) NULL,
    mfa_key_version SMALLINT UNSIGNED NULL,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_uuid (uuid),
    UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tenant_memberships (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    role ENUM('agency_owner', 'agency_admin', 'manager', 'analyst', 'client_viewer') NOT NULL,
    status ENUM('active', 'invited', 'disabled') NOT NULL DEFAULT 'active',
    invited_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_membership_tenant_user (tenant_id, user_id),
    KEY idx_membership_user (user_id),
    CONSTRAINT fk_membership_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_membership_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE auth_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    active_tenant_id BIGINT UNSIGNED NULL,
    active_membership_id BIGINT UNSIGNED NULL,
    session_token_hash CHAR(64) NOT NULL,
    csrf_token_hash CHAR(64) NULL,
    mfa_verified_at DATETIME NULL,
    ip_hash CHAR(64) NULL,
    user_agent_hash CHAR(64) NULL,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    revoked_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_auth_sessions_token (session_token_hash),
    KEY idx_auth_sessions_user (user_id, revoked_at, expires_at),
    KEY idx_auth_sessions_active_tenant (active_tenant_id, revoked_at, expires_at),
    CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_auth_sessions_tenant FOREIGN KEY (active_tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_auth_sessions_membership FOREIGN KEY (active_membership_id) REFERENCES tenant_memberships(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE password_reset_tokens (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL,
    requested_ip_hash CHAR(64) NULL,
    expires_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_password_reset_tokens_token (token_hash),
    KEY idx_password_reset_tokens_user (user_id, expires_at, used_at),
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE clients (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    legal_name VARCHAR(191) NULL,
    status ENUM('active', 'paused', 'archived') NOT NULL DEFAULT 'active',
    timezone VARCHAR(64) NOT NULL DEFAULT 'America/Sao_Paulo',
    reporting_currency_code CHAR(3) NOT NULL DEFAULT 'BRL',
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_clients_tenant_name (tenant_id, name),
    KEY idx_clients_tenant_status (tenant_id, status),
    CONSTRAINT fk_clients_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE client_access (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    membership_id BIGINT UNSIGNED NOT NULL,
    access_level ENUM('admin', 'manager', 'analyst', 'viewer') NOT NULL DEFAULT 'viewer',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_client_access (client_id, membership_id),
    KEY idx_client_access_tenant_membership (tenant_id, membership_id),
    CONSTRAINT fk_client_access_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_client_access_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_client_access_membership FOREIGN KEY (membership_id) REFERENCES tenant_memberships(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE google_ads_connections (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NULL,
    oauth_subject VARCHAR(191) NOT NULL,
    google_email VARCHAR(191) NULL,
    manager_customer_id BIGINT UNSIGNED NULL,
    login_customer_id BIGINT UNSIGNED NULL,
    developer_token_alias VARCHAR(64) NULL,
    refresh_token_ciphertext MEDIUMBLOB NOT NULL,
    refresh_token_iv VARBINARY(64) NOT NULL,
    refresh_token_tag VARBINARY(64) NOT NULL,
    token_key_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    scopes_json JSON NULL,
    status ENUM('active', 'paused', 'revoked', 'error') NOT NULL DEFAULT 'active',
    last_token_check_at DATETIME NULL,
    last_sync_at DATETIME NULL,
    sync_frequency_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 180,
    created_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_google_ads_connection_subject (tenant_id, oauth_subject),
    KEY idx_google_ads_connection_status (tenant_id, status),
    KEY idx_google_ads_connection_client (tenant_id, client_id),
    CONSTRAINT fk_google_ads_connection_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_google_ads_connection_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_google_ads_connection_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE google_ads_accounts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    connection_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    customer_name VARCHAR(191) NULL,
    descriptive_name VARCHAR(191) NULL,
    currency_code CHAR(3) NOT NULL,
    time_zone VARCHAR(64) NOT NULL,
    status ENUM('active', 'paused', 'removed', 'disconnected') NOT NULL DEFAULT 'active',
    is_manager TINYINT(1) NOT NULL DEFAULT 0,
    is_test_account TINYINT(1) NOT NULL DEFAULT 0,
    last_metadata_sync_at DATETIME NULL,
    last_metric_sync_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_google_ads_account_customer (tenant_id, customer_id),
    KEY idx_google_ads_accounts_client (tenant_id, client_id, status),
    KEY idx_google_ads_accounts_sync (tenant_id, last_metric_sync_at),
    CONSTRAINT fk_google_ads_account_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_google_ads_account_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_google_ads_account_connection FOREIGN KEY (connection_id) REFERENCES google_ads_connections(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE client_kpi_targets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    effective_from DATE NOT NULL,
    target_cpa DECIMAL(18, 2) NULL,
    target_roas DECIMAL(10, 4) NULL,
    target_ctr DECIMAL(10, 6) NULL,
    min_conversions_for_confidence INT UNSIGNED NOT NULL DEFAULT 5,
    alert_thresholds_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_client_kpi_targets (tenant_id, client_id, effective_from),
    CONSTRAINT fk_client_kpi_targets_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_client_kpi_targets_client FOREIGN KEY (client_id) REFERENCES clients(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dim_campaigns (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    google_campaign_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(191) NOT NULL,
    advertising_channel_type VARCHAR(64) NULL,
    bidding_strategy_type VARCHAR(64) NULL,
    status VARCHAR(32) NOT NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    source_updated_at DATETIME NULL,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_dim_campaigns (tenant_id, google_ads_account_id, google_campaign_id),
    KEY idx_dim_campaigns_client (tenant_id, client_id, status),
    CONSTRAINT fk_dim_campaigns_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_dim_campaigns_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_dim_campaigns_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dim_ad_groups (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    campaign_dim_id BIGINT UNSIGNED NOT NULL,
    google_ad_group_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(191) NOT NULL,
    status VARCHAR(32) NOT NULL,
    type VARCHAR(64) NULL,
    source_updated_at DATETIME NULL,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_dim_ad_groups (tenant_id, google_ads_account_id, google_ad_group_id),
    KEY idx_dim_ad_groups_campaign (tenant_id, campaign_dim_id, status),
    CONSTRAINT fk_dim_ad_groups_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_dim_ad_groups_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_dim_ad_groups_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_dim_ad_groups_campaign FOREIGN KEY (campaign_dim_id) REFERENCES dim_campaigns(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dim_keywords (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    ad_group_dim_id BIGINT UNSIGNED NOT NULL,
    google_keyword_criterion_id BIGINT UNSIGNED NOT NULL,
    keyword_text VARCHAR(255) NOT NULL,
    match_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    source_updated_at DATETIME NULL,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_dim_keywords (tenant_id, google_ads_account_id, google_keyword_criterion_id),
    KEY idx_dim_keywords_ad_group (tenant_id, ad_group_dim_id, status),
    CONSTRAINT fk_dim_keywords_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_dim_keywords_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_dim_keywords_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_dim_keywords_ad_group FOREIGN KEY (ad_group_dim_id) REFERENCES dim_ad_groups(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fact_google_ads_account_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions DECIMAL(18, 4) NOT NULL DEFAULT 0,
    conversions_value DECIMAL(18, 4) NOT NULL DEFAULT 0,
    ctr DECIMAL(12, 6) NULL,
    average_cpc DECIMAL(18, 6) NULL,
    average_cpm DECIMAL(18, 6) NULL,
    search_impression_share DECIMAL(10, 6) NULL,
    search_budget_lost_impression_share DECIMAL(10, 6) NULL,
    search_rank_lost_impression_share DECIMAL(10, 6) NULL,
    synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fact_account_daily (tenant_id, google_ads_account_id, report_date),
    KEY idx_fact_account_daily_client_date (tenant_id, client_id, report_date),
    CONSTRAINT fk_fact_account_daily_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_fact_account_daily_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_fact_account_daily_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fact_google_ads_account_intraday (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    snapshot_at DATETIME NOT NULL,
    snapshot_date DATE NOT NULL,
    snapshot_hour TINYINT UNSIGNED NOT NULL,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions DECIMAL(18, 4) NOT NULL DEFAULT 0,
    conversions_value DECIMAL(18, 4) NOT NULL DEFAULT 0,
    synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fact_account_intraday (tenant_id, google_ads_account_id, snapshot_at),
    KEY idx_fact_account_intraday_client_time (tenant_id, client_id, snapshot_date, snapshot_hour),
    CONSTRAINT fk_fact_account_intraday_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_fact_account_intraday_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_fact_account_intraday_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fact_google_ads_campaign_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    campaign_dim_id BIGINT UNSIGNED NULL,
    google_campaign_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions DECIMAL(18, 4) NOT NULL DEFAULT 0,
    conversions_value DECIMAL(18, 4) NOT NULL DEFAULT 0,
    ctr DECIMAL(12, 6) NULL,
    average_cpc DECIMAL(18, 6) NULL,
    average_cpm DECIMAL(18, 6) NULL,
    search_impression_share DECIMAL(10, 6) NULL,
    search_budget_lost_impression_share DECIMAL(10, 6) NULL,
    search_rank_lost_impression_share DECIMAL(10, 6) NULL,
    synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fact_campaign_daily (tenant_id, google_ads_account_id, google_campaign_id, report_date),
    KEY idx_fact_campaign_daily_client_date (tenant_id, client_id, report_date),
    KEY idx_fact_campaign_daily_campaign_date (tenant_id, google_campaign_id, report_date),
    CONSTRAINT fk_fact_campaign_daily_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_fact_campaign_daily_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_fact_campaign_daily_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_fact_campaign_daily_campaign_dim FOREIGN KEY (campaign_dim_id) REFERENCES dim_campaigns(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fact_google_ads_campaign_intraday (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    google_campaign_id BIGINT UNSIGNED NOT NULL,
    snapshot_at DATETIME NOT NULL,
    snapshot_date DATE NOT NULL,
    snapshot_hour TINYINT UNSIGNED NOT NULL,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions DECIMAL(18, 4) NOT NULL DEFAULT 0,
    conversions_value DECIMAL(18, 4) NOT NULL DEFAULT 0,
    synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fact_campaign_intraday (tenant_id, google_ads_account_id, google_campaign_id, snapshot_at),
    KEY idx_fact_campaign_intraday_client_time (tenant_id, client_id, snapshot_date, snapshot_hour),
    CONSTRAINT fk_fact_campaign_intraday_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_fact_campaign_intraday_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_fact_campaign_intraday_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fact_google_ads_campaign_device_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    google_campaign_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    device_type VARCHAR(32) NOT NULL,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions DECIMAL(18, 4) NOT NULL DEFAULT 0,
    conversions_value DECIMAL(18, 4) NOT NULL DEFAULT 0,
    ctr DECIMAL(12, 6) NULL,
    average_cpc DECIMAL(18, 6) NULL,
    synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fact_campaign_device_daily (tenant_id, google_ads_account_id, google_campaign_id, report_date, device_type),
    KEY idx_fact_campaign_device_client_date (tenant_id, client_id, report_date),
    CONSTRAINT fk_fact_campaign_device_daily_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_fact_campaign_device_daily_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_fact_campaign_device_daily_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fact_google_ads_campaign_geo_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    google_campaign_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    geo_target_type VARCHAR(32) NOT NULL,
    geo_target_id BIGINT UNSIGNED NULL,
    geo_label VARCHAR(191) NOT NULL,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions DECIMAL(18, 4) NOT NULL DEFAULT 0,
    conversions_value DECIMAL(18, 4) NOT NULL DEFAULT 0,
    synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fact_campaign_geo_daily (tenant_id, google_ads_account_id, google_campaign_id, report_date, geo_target_type, geo_label),
    KEY idx_fact_campaign_geo_client_date (tenant_id, client_id, report_date),
    CONSTRAINT fk_fact_campaign_geo_daily_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_fact_campaign_geo_daily_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_fact_campaign_geo_daily_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fact_google_ads_campaign_hourly (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    google_campaign_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    hour_of_day TINYINT UNSIGNED NOT NULL,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions DECIMAL(18, 4) NOT NULL DEFAULT 0,
    conversions_value DECIMAL(18, 4) NOT NULL DEFAULT 0,
    synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_fact_campaign_hourly (tenant_id, google_ads_account_id, google_campaign_id, report_date, hour_of_day),
    KEY idx_fact_campaign_hourly_client_date (tenant_id, client_id, report_date),
    CONSTRAINT fk_fact_campaign_hourly_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_fact_campaign_hourly_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_fact_campaign_hourly_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sync_cursors (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    entity_name VARCHAR(64) NOT NULL,
    cursor_date DATE NULL,
    cursor_datetime DATETIME NULL,
    last_success_at DATETIME NULL,
    last_status ENUM('idle', 'running', 'succeeded', 'failed', 'partial') NOT NULL DEFAULT 'idle',
    cursor_meta_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sync_cursor (tenant_id, google_ads_account_id, entity_name),
    CONSTRAINT fk_sync_cursor_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sync_cursor_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sync_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    job_type ENUM(
        'account_discovery',
        'metadata_change_scan',
        'metadata_refresh',
        'initial_backfill_account_daily',
        'initial_backfill_campaign_daily',
        'initial_backfill_campaign_device_daily',
        'initial_backfill_campaign_hourly',
        'initial_backfill_campaign_geo_daily',
        'intraday_account',
        'intraday_campaign',
        'daily_account',
        'daily_campaign',
        'daily_campaign_device',
        'daily_campaign_hourly',
        'daily_campaign_geo',
        'daily_search_term',
        'recent_reprocess_account',
        'recent_reprocess_campaign',
        'recent_reprocess_campaign_device',
        'recent_reprocess_campaign_hourly',
        'recent_reprocess_campaign_geo',
        'recent_reprocess_search_term',
        'aggregation',
        'insight_generation',
        'slide_generation'
    ) NOT NULL,
    queue_name VARCHAR(64) NOT NULL DEFAULT 'default',
    status ENUM('queued', 'running', 'succeeded', 'failed', 'partial', 'cancelled') NOT NULL DEFAULT 'queued',
    priority TINYINT UNSIGNED NOT NULL DEFAULT 5,
    triggered_by ENUM('scheduler', 'manual', 'retry', 'system') NOT NULL DEFAULT 'scheduler',
    scheduled_for DATETIME NOT NULL,
    dedupe_key CHAR(64) NULL,
    concurrency_key VARCHAR(191) NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    attempt_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts TINYINT UNSIGNED NOT NULL DEFAULT 3,
    lease_token CHAR(36) NULL,
    lease_expires_at DATETIME NULL,
    request_window_start DATE NULL,
    request_window_end DATE NULL,
    cursor_payload_json JSON NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(500) NULL,
    error_context_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_sync_jobs_lookup (tenant_id, status, scheduled_for),
    KEY idx_sync_jobs_queue_status (queue_name, status, scheduled_for),
    KEY idx_sync_jobs_account (google_ads_account_id, job_type, status),
    KEY idx_sync_jobs_dedupe (tenant_id, dedupe_key),
    KEY idx_sync_jobs_concurrency (concurrency_key, status, lease_expires_at),
    CONSTRAINT fk_sync_jobs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sync_jobs_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_sync_jobs_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sync_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    sync_job_id BIGINT UNSIGNED NULL,
    run_uuid CHAR(36) NOT NULL,
    job_type VARCHAR(80) NOT NULL,
    entity_scope VARCHAR(64) NOT NULL,
    status ENUM('running', 'succeeded', 'failed', 'partial', 'cancelled') NOT NULL DEFAULT 'running',
    attempt_number TINYINT UNSIGNED NOT NULL DEFAULT 1,
    request_window_start DATE NULL,
    request_window_end DATE NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    rows_read BIGINT UNSIGNED NOT NULL DEFAULT 0,
    rows_inserted BIGINT UNSIGNED NOT NULL DEFAULT 0,
    rows_updated BIGINT UNSIGNED NOT NULL DEFAULT 0,
    rows_upserted BIGINT UNSIGNED NOT NULL DEFAULT 0,
    rows_skipped BIGINT UNSIGNED NOT NULL DEFAULT 0,
    api_request_count INT UNSIGNED NOT NULL DEFAULT 0,
    api_operation_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_google_request_id VARCHAR(120) NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(500) NULL,
    error_context_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sync_runs_uuid (run_uuid),
    KEY idx_sync_runs_lookup (tenant_id, status, started_at),
    KEY idx_sync_runs_account_scope (google_ads_account_id, entity_scope, started_at),
    KEY idx_sync_runs_job (sync_job_id, attempt_number),
    CONSTRAINT fk_sync_runs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sync_runs_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_sync_runs_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_sync_runs_job FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sync_checkpoints (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NULL,
    google_ads_account_id BIGINT UNSIGNED NOT NULL,
    checkpoint_scope ENUM(
        'metadata',
        'account_daily',
        'campaign_daily',
        'campaign_device_daily',
        'campaign_hourly',
        'campaign_geo_daily',
        'search_term_daily',
        'intraday_account',
        'intraday_campaign'
    ) NOT NULL,
    checkpoint_key VARCHAR(191) NOT NULL,
    watermark_date DATE NULL,
    watermark_datetime DATETIME NULL,
    safe_reprocess_from DATE NULL,
    last_complete_date DATE NULL,
    last_status ENUM('idle', 'running', 'succeeded', 'failed', 'partial') NOT NULL DEFAULT 'idle',
    last_success_run_id BIGINT UNSIGNED NULL,
    checkpoint_meta_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sync_checkpoints (tenant_id, google_ads_account_id, checkpoint_scope, checkpoint_key),
    KEY idx_sync_checkpoints_lookup (tenant_id, google_ads_account_id, checkpoint_scope, last_complete_date),
    CONSTRAINT fk_sync_checkpoints_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_sync_checkpoints_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_sync_checkpoints_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_sync_checkpoints_run FOREIGN KEY (last_success_run_id) REFERENCES sync_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE api_request_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    sync_job_id BIGINT UNSIGNED NULL,
    sync_run_id BIGINT UNSIGNED NULL,
    request_scope ENUM('metadata', 'metrics', 'reprocess', 'search_term') NOT NULL,
    api_method ENUM('search', 'search_stream', 'get', 'mutate') NOT NULL DEFAULT 'search_stream',
    resource_name VARCHAR(80) NOT NULL,
    google_request_id VARCHAR(120) NULL,
    gaql_fingerprint CHAR(64) NULL,
    gaql_query_excerpt VARCHAR(500) NULL,
    date_from DATE NULL,
    date_to DATE NULL,
    http_status SMALLINT UNSIGNED NULL,
    grpc_status_code VARCHAR(64) NULL,
    success TINYINT(1) NOT NULL DEFAULT 1,
    retry_attempt TINYINT UNSIGNED NOT NULL DEFAULT 0,
    duration_ms INT UNSIGNED NOT NULL,
    response_row_count INT UNSIGNED NULL,
    response_batch_count INT UNSIGNED NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(500) NULL,
    requested_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_api_request_logs_tenant_time (tenant_id, requested_at),
    KEY idx_api_request_logs_account_time (google_ads_account_id, requested_at),
    KEY idx_api_request_logs_request_id (google_request_id),
    KEY idx_api_request_logs_sync_run (sync_run_id),
    CONSTRAINT fk_api_request_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_api_request_logs_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_api_request_logs_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_api_request_logs_job FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id),
    CONSTRAINT fk_api_request_logs_run FOREIGN KEY (sync_run_id) REFERENCES sync_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dead_letter_queue (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    sync_job_id BIGINT UNSIGNED NULL,
    sync_run_id BIGINT UNSIGNED NULL,
    dedupe_key CHAR(64) NULL,
    failure_class ENUM('auth', 'quota', 'retry_exhausted', 'validation', 'sync', 'unknown') NOT NULL,
    failure_reason VARCHAR(500) NOT NULL,
    payload_json JSON NULL,
    resolution_status ENUM('open', 'requeued', 'discarded', 'resolved') NOT NULL DEFAULT 'open',
    next_review_at DATETIME NULL,
    resolved_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_dead_letter_queue_tenant_status (tenant_id, resolution_status, created_at),
    KEY idx_dead_letter_queue_account_status (google_ads_account_id, resolution_status, created_at),
    CONSTRAINT fk_dead_letter_queue_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_dead_letter_queue_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_dead_letter_queue_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_dead_letter_queue_job FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id),
    CONSTRAINT fk_dead_letter_queue_run FOREIGN KEY (sync_run_id) REFERENCES sync_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agg_client_kpi_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    report_date DATE NOT NULL,
    spend DECIMAL(18, 2) NOT NULL DEFAULT 0,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions DECIMAL(18, 4) NOT NULL DEFAULT 0,
    conversions_value DECIMAL(18, 4) NOT NULL DEFAULT 0,
    ctr DECIMAL(12, 6) NULL,
    cpa DECIMAL(18, 6) NULL,
    roas DECIMAL(18, 6) NULL,
    synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_agg_client_kpi_daily (tenant_id, client_id, report_date),
    KEY idx_agg_client_kpi_daily_client_date (tenant_id, client_id, report_date),
    CONSTRAINT fk_agg_client_kpi_daily_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_agg_client_kpi_daily_client FOREIGN KEY (client_id) REFERENCES clients(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agg_client_kpi_period (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    period_type ENUM('last_7d', 'last_30d', 'month_to_date', 'custom') NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    spend DECIMAL(18, 2) NOT NULL DEFAULT 0,
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    conversions DECIMAL(18, 4) NOT NULL DEFAULT 0,
    conversions_value DECIMAL(18, 4) NOT NULL DEFAULT 0,
    ctr DECIMAL(12, 6) NULL,
    cpa DECIMAL(18, 6) NULL,
    roas DECIMAL(18, 6) NULL,
    generated_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_agg_client_kpi_period (tenant_id, client_id, period_type, period_start, period_end),
    KEY idx_agg_client_kpi_period_client_range (tenant_id, client_id, period_start, period_end),
    CONSTRAINT fk_agg_client_kpi_period_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_agg_client_kpi_period_client FOREIGN KEY (client_id) REFERENCES clients(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE insight_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    baseline_start DATE NULL,
    baseline_end DATE NULL,
    comparison_label VARCHAR(120) NULL,
    generated_by ENUM('system', 'user') NOT NULL DEFAULT 'system',
    triggered_by_user_id BIGINT UNSIGNED NULL,
    previous_run_id BIGINT UNSIGNED NULL,
    orchestrator_run_uuid CHAR(36) NULL,
    run_hash CHAR(64) NULL,
    status ENUM('queued', 'running', 'completed', 'failed') NOT NULL DEFAULT 'queued',
    summary_json JSON NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_insight_runs_client_period (tenant_id, client_id, period_start, period_end),
    KEY idx_insight_runs_account_period (tenant_id, google_ads_account_id, period_start, period_end),
    KEY idx_insight_runs_orchestrator (orchestrator_run_uuid),
    CONSTRAINT fk_insight_runs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_insight_runs_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_insight_runs_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_insight_runs_user FOREIGN KEY (triggered_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_insight_runs_previous FOREIGN KEY (previous_run_id) REFERENCES insight_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE insights (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    insight_run_id BIGINT UNSIGNED NOT NULL,
    insight_key CHAR(64) NOT NULL,
    scope_type ENUM('account', 'campaign', 'device', 'geo', 'schedule', 'keyword', 'search_term', 'tracking') NOT NULL,
    scope_ref VARCHAR(120) NOT NULL,
    category VARCHAR(64) NOT NULL,
    severity ENUM('info', 'warning', 'critical') NOT NULL DEFAULT 'warning',
    confidence_band ENUM('low', 'moderate', 'high', 'very_high') NULL,
    summary TEXT NOT NULL,
    diagnosis TEXT NOT NULL,
    primary_hypothesis TEXT NULL,
    alternative_hypotheses_json JSON NULL,
    source_agent_names_json JSON NULL,
    hypothesis_status ENUM('confirmed', 'plausible', 'weak', 'insufficient_evidence') NULL,
    title VARCHAR(191) NOT NULL,
    explanation_short TEXT NOT NULL,
    explanation_exec TEXT NULL,
    recommendation_action ENUM(
        'increase_budget',
        'decrease_budget',
        'pause',
        'shift_device',
        'shift_schedule',
        'shift_geo',
        'review_tracking',
        'review_keywords',
        'review_landing_page'
    ) NOT NULL,
    priority ENUM('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium',
    priority_score DECIMAL(6, 2) NOT NULL DEFAULT 0,
    confidence DECIMAL(4, 3) NOT NULL,
    estimated_monthly_impact DECIMAL(18, 2) NULL,
    risk_level ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
    evidence_json JSON NULL,
    blocked_claims_json JSON NULL,
    next_steps_json JSON NULL,
    review_notes_json JSON NULL,
    period_reference_json JSON NULL,
    current_payload_json JSON NULL,
    current_version_number INT UNSIGNED NOT NULL DEFAULT 1,
    latest_version_id BIGINT UNSIGNED NULL,
    latest_run_id BIGINT UNSIGNED NULL,
    status ENUM('open', 'accepted', 'dismissed', 'implemented') NOT NULL DEFAULT 'open',
    generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_insights_key (tenant_id, insight_key),
    KEY idx_insights_client_status (tenant_id, client_id, status, priority),
    KEY idx_insights_account_category (tenant_id, google_ads_account_id, category, severity),
    KEY idx_insights_run (insight_run_id),
    KEY idx_insights_latest_version (latest_version_id),
    KEY idx_insights_latest_run (latest_run_id),
    CONSTRAINT fk_insights_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_insights_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_insights_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_insights_run FOREIGN KEY (insight_run_id) REFERENCES insight_runs(id),
    CONSTRAINT fk_insights_latest_run FOREIGN KEY (latest_run_id) REFERENCES insight_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE insight_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    insight_id BIGINT UNSIGNED NOT NULL,
    insight_run_id BIGINT UNSIGNED NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    payload_schema_version VARCHAR(16) NOT NULL DEFAULT '1.0',
    payload_hash CHAR(64) NOT NULL,
    content_hash CHAR(64) NOT NULL,
    entity_type ENUM('account', 'campaign', 'device', 'geo', 'schedule', 'keyword', 'search_term', 'tracking') NOT NULL,
    entity_id VARCHAR(120) NOT NULL,
    category VARCHAR(64) NOT NULL,
    severity ENUM('info', 'warning', 'critical') NOT NULL,
    priority_score DECIMAL(6, 2) NOT NULL,
    confidence_score DECIMAL(6, 4) NOT NULL,
    confidence_band ENUM('low', 'moderate', 'high', 'very_high') NULL,
    risk_level ENUM('low', 'medium', 'high') NOT NULL,
    source_agent_names_json JSON NULL,
    hypothesis_status ENUM('confirmed', 'plausible', 'weak', 'insufficient_evidence') NULL,
    review_notes_json JSON NULL,
    period_reference_json JSON NOT NULL,
    payload_json JSON NOT NULL,
    generated_at DATETIME NOT NULL,
    supersedes_version_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_insight_versions_version (insight_id, version_number),
    UNIQUE KEY uq_insight_versions_content (insight_id, content_hash),
    KEY idx_insight_versions_lookup (tenant_id, client_id, insight_id, version_number),
    KEY idx_insight_versions_account (tenant_id, google_ads_account_id, category, generated_at),
    CONSTRAINT fk_insight_versions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_insight_versions_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_insight_versions_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_insight_versions_insight FOREIGN KEY (insight_id) REFERENCES insights(id),
    CONSTRAINT fk_insight_versions_run FOREIGN KEY (insight_run_id) REFERENCES insight_runs(id),
    CONSTRAINT fk_insight_versions_supersedes FOREIGN KEY (supersedes_version_id) REFERENCES insight_versions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE insight_run_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    insight_run_id BIGINT UNSIGNED NOT NULL,
    insight_id BIGINT UNSIGNED NOT NULL,
    insight_version_id BIGINT UNSIGNED NULL,
    insight_key CHAR(64) NOT NULL,
    scope_type ENUM('account', 'campaign', 'device', 'geo', 'schedule', 'keyword', 'search_term', 'tracking') NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id VARCHAR(120) NOT NULL,
    category VARCHAR(64) NOT NULL,
    severity ENUM('info', 'warning', 'critical') NOT NULL,
    hypothesis_status ENUM('confirmed', 'plausible', 'weak', 'insufficient_evidence') NULL,
    priority_score DECIMAL(6, 2) NOT NULL,
    confidence_score DECIMAL(6, 4) NOT NULL,
    run_change_type ENUM('new', 'updated', 'unchanged') NOT NULL DEFAULT 'unchanged',
    payload_hash CHAR(64) NOT NULL,
    content_hash CHAR(64) NOT NULL,
    title VARCHAR(191) NOT NULL,
    payload_json JSON NOT NULL,
    generated_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_insight_run_items_run_key (insight_run_id, insight_key),
    KEY idx_insight_run_items_lookup (tenant_id, client_id, insight_run_id, category),
    KEY idx_insight_run_items_account (tenant_id, google_ads_account_id, generated_at),
    KEY idx_insight_run_items_insight (insight_id, insight_version_id),
    CONSTRAINT fk_insight_run_items_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_insight_run_items_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_insight_run_items_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_insight_run_items_run FOREIGN KEY (insight_run_id) REFERENCES insight_runs(id),
    CONSTRAINT fk_insight_run_items_insight FOREIGN KEY (insight_id) REFERENCES insights(id),
    CONSTRAINT fk_insight_run_items_version FOREIGN KEY (insight_version_id) REFERENCES insight_versions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE insights
    ADD CONSTRAINT fk_insights_latest_version FOREIGN KEY (latest_version_id) REFERENCES insight_versions(id);

CREATE TABLE agent_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    insight_run_id BIGINT UNSIGNED NOT NULL,
    orchestrator_run_uuid CHAR(36) NOT NULL,
    agent_name VARCHAR(64) NOT NULL,
    agent_version VARCHAR(32) NOT NULL,
    dedupe_key CHAR(64) NOT NULL,
    status ENUM('queued', 'running', 'ready', 'partial', 'skipped', 'insufficient_data', 'failed') NOT NULL DEFAULT 'queued',
    analysis_window_json JSON NOT NULL,
    data_quality_json JSON NOT NULL,
    priority_score DECIMAL(6, 2) NULL,
    confidence_score DECIMAL(6, 4) NULL,
    summary TEXT NULL,
    recommended_focus TEXT NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(255) NULL,
    output_hash CHAR(64) NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_agent_runs_dedupe (insight_run_id, agent_name, dedupe_key),
    KEY idx_agent_runs_orchestrator (orchestrator_run_uuid),
    KEY idx_agent_runs_lookup (tenant_id, client_id, insight_run_id, agent_name, status),
    CONSTRAINT fk_agent_runs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_agent_runs_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_agent_runs_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_agent_runs_insight_run FOREIGN KEY (insight_run_id) REFERENCES insight_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agent_run_outputs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    agent_run_id BIGINT UNSIGNED NOT NULL,
    insight_run_id BIGINT UNSIGNED NULL,
    payload_schema_version VARCHAR(16) NOT NULL DEFAULT '1.0',
    output_status VARCHAR(32) NULL,
    output_hash CHAR(64) NULL,
    summary_text TEXT NULL,
    output_json JSON NOT NULL,
    candidate_entity_count INT UNSIGNED NOT NULL DEFAULT 0,
    findings_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_agent_run_outputs_agent_run (agent_run_id, created_at),
    KEY idx_agent_run_outputs_run (insight_run_id, created_at),
    CONSTRAINT fk_agent_run_outputs_insight_run FOREIGN KEY (insight_run_id) REFERENCES insight_runs(id),
    CONSTRAINT fk_agent_run_outputs_agent_run FOREIGN KEY (agent_run_id) REFERENCES agent_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agent_findings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    insight_run_id BIGINT UNSIGNED NOT NULL,
    agent_run_id BIGINT UNSIGNED NOT NULL,
    finding_key CHAR(64) NOT NULL,
    source_agent_name VARCHAR(64) NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id VARCHAR(120) NOT NULL,
    entity_label VARCHAR(191) NULL,
    category VARCHAR(64) NOT NULL,
    severity ENUM('info', 'warning', 'critical') NOT NULL,
    priority_band ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    priority_score DECIMAL(6, 2) NOT NULL,
    confidence_band ENUM('low', 'moderate', 'high', 'very_high') NOT NULL,
    confidence_score DECIMAL(6, 4) NOT NULL,
    risk_level ENUM('low', 'medium', 'high') NOT NULL,
    title VARCHAR(191) NOT NULL,
    summary TEXT NOT NULL,
    diagnosis TEXT NOT NULL,
    primary_hypothesis TEXT NOT NULL,
    support_agent_names_json JSON NOT NULL,
    alternative_hypotheses_json JSON NOT NULL,
    hypothesis_status ENUM('confirmed', 'plausible', 'weak', 'insufficient_evidence') NOT NULL DEFAULT 'plausible',
    recommended_action_json JSON NOT NULL,
    expected_impact TEXT NOT NULL,
    technical_explanation TEXT NOT NULL,
    executive_explanation TEXT NOT NULL,
    evidence_json JSON NOT NULL,
    data_gaps_json JSON NOT NULL,
    tags_json JSON NOT NULL,
    review_notes_json JSON NOT NULL,
    status ENUM('open', 'accepted', 'dismissed', 'superseded') NOT NULL DEFAULT 'open',
    content_hash CHAR(64) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_agent_findings_run_key (agent_run_id, finding_key),
    KEY idx_agent_findings_lookup (tenant_id, client_id, entity_type, entity_id, category),
    KEY idx_agent_findings_run (insight_run_id, source_agent_name, severity),
    CONSTRAINT fk_agent_findings_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_agent_findings_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_agent_findings_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_agent_findings_insight_run FOREIGN KEY (insight_run_id) REFERENCES insight_runs(id),
    CONSTRAINT fk_agent_findings_agent_run FOREIGN KEY (agent_run_id) REFERENCES agent_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agent_conflicts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    google_ads_account_id BIGINT UNSIGNED NULL,
    insight_run_id BIGINT UNSIGNED NOT NULL,
    orchestrator_run_uuid CHAR(36) NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id VARCHAR(120) NOT NULL,
    conflict_type VARCHAR(80) NOT NULL,
    source_agents_json JSON NOT NULL,
    resolution TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_agent_conflicts_lookup (tenant_id, client_id, insight_run_id, entity_type, entity_id),
    KEY idx_agent_conflicts_orchestrator (orchestrator_run_uuid),
    CONSTRAINT fk_agent_conflicts_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_agent_conflicts_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_agent_conflicts_account FOREIGN KEY (google_ads_account_id) REFERENCES google_ads_accounts(id),
    CONSTRAINT fk_agent_conflicts_insight_run FOREIGN KEY (insight_run_id) REFERENCES insight_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE executive_reports (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NOT NULL,
    client_id BIGINT UNSIGNED NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    audience_level ENUM('executive', 'marketing', 'technical') NOT NULL DEFAULT 'executive',
    status ENUM('queued', 'generating', 'ready', 'failed') NOT NULL DEFAULT 'queued',
    output_format ENUM('pptx', 'pdf', 'html') NOT NULL DEFAULT 'pptx',
    storage_path VARCHAR(255) NULL,
    summary_json JSON NULL,
    generated_by_user_id BIGINT UNSIGNED NULL,
    generated_at DATETIME NULL,
    expires_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_executive_reports_client_period (tenant_id, client_id, period_start, period_end),
    CONSTRAINT fk_executive_reports_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_executive_reports_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_executive_reports_user FOREIGN KEY (generated_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE security_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NULL,
    client_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    actor_membership_id BIGINT UNSIGNED NULL,
    auth_session_id BIGINT UNSIGNED NULL,
    request_id CHAR(36) NULL,
    correlation_id CHAR(36) NULL,
    event_key CHAR(64) NULL,
    event_name VARCHAR(120) NOT NULL,
    event_category ENUM('auth', 'session', 'access', 'tenant', 'oauth', 'token', 'mfa', 'csrf', 'rate_limit', 'security_policy') NOT NULL,
    severity ENUM('info', 'warn', 'high', 'critical') NOT NULL DEFAULT 'info',
    outcome ENUM('success', 'failure', 'blocked') NOT NULL,
    actor_type ENUM('anonymous', 'user', 'superadmin', 'system', 'worker', 'scheduler', 'api') NOT NULL DEFAULT 'anonymous',
    source_type ENUM('web', 'api', 'worker', 'scheduler', 'system') NOT NULL DEFAULT 'api',
    resource_type VARCHAR(80) NULL,
    resource_id VARCHAR(120) NULL,
    http_method VARCHAR(10) NULL,
    route_path VARCHAR(191) NULL,
    ip_hash CHAR(64) NULL,
    user_agent_hash CHAR(64) NULL,
    metadata_json JSON NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_security_events_event_key (event_key),
    KEY idx_security_events_tenant_category_occurred (tenant_id, event_category, occurred_at),
    KEY idx_security_events_client_occurred (tenant_id, client_id, occurred_at),
    KEY idx_security_events_user_event_occurred (user_id, event_name, occurred_at),
    KEY idx_security_events_session_occurred (auth_session_id, occurred_at),
    KEY idx_security_events_request (request_id),
    KEY idx_security_events_correlation (correlation_id),
    CONSTRAINT fk_security_events_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_security_events_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_security_events_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_security_events_membership FOREIGN KEY (actor_membership_id) REFERENCES tenant_memberships(id),
    CONSTRAINT fk_security_events_session FOREIGN KEY (auth_session_id) REFERENCES auth_sessions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT UNSIGNED NULL,
    client_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    actor_membership_id BIGINT UNSIGNED NULL,
    auth_session_id BIGINT UNSIGNED NULL,
    request_id CHAR(36) NULL,
    correlation_id CHAR(36) NULL,
    event_key CHAR(64) NULL,
    event_name VARCHAR(120) NOT NULL,
    event_category ENUM('google_ads', 'sync', 'insight', 'report', 'export', 'permission', 'configuration', 'manual_action', 'support') NOT NULL,
    severity ENUM('info', 'warn', 'high', 'critical') NOT NULL DEFAULT 'info',
    outcome ENUM('success', 'failure', 'blocked') NOT NULL DEFAULT 'success',
    actor_type ENUM('user', 'superadmin', 'system', 'worker', 'scheduler', 'api') NOT NULL DEFAULT 'system',
    source_type ENUM('web', 'api', 'worker', 'scheduler', 'system') NOT NULL DEFAULT 'api',
    actor_role VARCHAR(40) NULL,
    resource_type VARCHAR(80) NULL,
    resource_id VARCHAR(120) NULL,
    http_method VARCHAR(10) NULL,
    route_path VARCHAR(191) NULL,
    ip_hash CHAR(64) NULL,
    user_agent_hash CHAR(64) NULL,
    before_json JSON NULL,
    after_json JSON NULL,
    metadata_json JSON NULL,
    redaction_level ENUM('none', 'masked', 'strict') NOT NULL DEFAULT 'masked',
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_audit_logs_event_key (event_key),
    KEY idx_audit_logs_tenant_category_occurred (tenant_id, event_category, occurred_at),
    KEY idx_audit_logs_client_occurred (tenant_id, client_id, occurred_at),
    KEY idx_audit_logs_user_occurred (user_id, occurred_at),
    KEY idx_audit_logs_resource_occurred (tenant_id, resource_type, resource_id, occurred_at),
    KEY idx_audit_logs_request (request_id),
    KEY idx_audit_logs_correlation (correlation_id),
    CONSTRAINT fk_audit_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_audit_logs_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_audit_logs_membership FOREIGN KEY (actor_membership_id) REFERENCES tenant_memberships(id),
    CONSTRAINT fk_audit_logs_session FOREIGN KEY (auth_session_id) REFERENCES auth_sessions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
